### ISSUE TITLE
Activity name with blanks doesn't collapse

### ISSUE THREAD

**Issue by kokosnuss** [DieKonsonanten/locator#25]

**Comment by karolinedigkaufer** [comment]
@kokosnuss Es dürften gar keine Blanks mehr verwendet werden... siehe https://github.com/DieKonsonanten/locator/blob/ae28c3957c21efa3e764d614ada5eeed0afb2fa8/lib/views/new_activity.erb#L20

Was mich nur wundern, bei mir lokal gibt es zusätzlich noch einen title="ohne Leerzeichen" und das Feld required. Dennoch konnte ich in meinem Test gerade keine Aktivität mit einem Leerzeichen hinzufügen?!

**Comment by M0P** [comment]
Ohne Leerzeichen sehen manche Titel einfach hässlich aus. Der eigentliche Bug ist hier, das die Formularfelder nur Frontendseitig geprüft werden und das Backend alles akzeptiert (was defacto sehr schlecht ist, weil man damit sehr böse Dinge tun könnte).

Hässliche Lösung:
Im Backend eine Prüfung auf die wichtigen Dinge einbauen (z.B. keine Leerzeichen)

schöne Lösung:
Wichtigen Dinge im Backend abfangen. Am Beispiel Leerzeichen: Einfach das Leerzeichen bei Link relevanten Dingen durch ein "_" ersetzen lassen. 

schönste Lösung =schöne Lösung + hässliche Lösung. Also die Prüfung auf jeden Fall im Backend durchführen. Bei Kleinigkeiten eigenständig fixen. Bei größerem Nutzer am Frontend informieren.

**Comment by M0P** [comment]
Passiert übrigens auch bei anderen Sonderzeichen. Sodass ein Escapen der Links auf jeden Fall passieren sollte.

Beispiel: "Klettern_(Halle)" - auf Website.
