### ISSUE TITLE
Abstimmung anpassen

### ISSUE THREAD

**Issue by karolinedigkaufer** [DieKonsonanten/locator#5]
- [x] max. 1 Stimme pro Unternehmung 
- [x] bis zu 3 Stimmen pro User
- [x] eigene Auswahl steht oben
- [x] die Antwortmöglichkeiten sind in alphabetischer Reihenfolge
- [x] über die Locations einer Unternehmung darf jeder entscheiden, auch wenn er nicht für die Unternehmung gestimmt hat. Dabei ist eine Stimme möglich

**Comment by Benedikt1992** [comment]
![abstimmungd](https://user-images.githubusercontent.com/5672310/30588755-41d77d46-9d38-11e7-894c-90b4a5e3a633.jpg)

**Comment by karolinedigkaufer** [comment]
Eigene Auswahl soll nicht mehr oben stehen, da die Slider übersichtlich genug sind.
