### ISSUE TITLE
Ergebnisseite anpassen

### ISSUE THREAD

**Issue by karolinedigkaufer** [DieKonsonanten/locator#7]
- Ergebnisse sollen als Balkendiagramm präsentiert werden (nur die Unternehmungen sichtbar, Infos über Location sind nicht abgebildet)
- ein Hover zeigt die Rangliste der möglichen Locations

**Comment by Benedikt1992** [comment]
![ergebnis](https://user-images.githubusercontent.com/5672310/30588785-65ad08b2-9d38-11e7-8b2e-467c50ba43f9.jpg)
